server:
  port : 5000
spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mysql://database-1.crhrin8dmx5c.ap-northeast-2.rds.amazonaws.com:3306/database-1
      username: root
      password: Wns1125218!